import { test, expect } from '@playwright/test';
test('coin overlay opens, handles dragging, closes and restores focus on mobile', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  let balance = 1250;
  await page.route('**/api/wallet', route => route.fulfill({ json: { wallet: { id: 'a', name: 'こども', balance, kanjiEnabled: false }, bank: { name: 'ぎんこう', currencyName: 'コイン', unit: 'COIN' }, wallets: [] } }));
  await page.route('**/api/wallet/history', route => route.fulfill({ json: { entries: [], nextCursor: null } }));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/wallet?k=test');
  const button = page.getByRole('button', { name: 'コインをみる' });
  await button.click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog).toContainText('1,250 COIN');
  await expect(dialog.locator('canvas')).toBeVisible();
  await expect(dialog.getByRole('status')).toHaveText('いちばんすくない · 5まい');
  const exchange = dialog.getByRole('button', { name: 'りょうがえ', exact: true });
  await exchange.click();
  await expect(dialog.getByRole('status')).toHaveText('すこしおおめ · 19まい');
  await exchange.click();
  await expect(dialog.getByRole('status')).toHaveText('たくさん · 43まい');
  await exchange.click();
  await expect(dialog.getByRole('status')).toHaveText('いちばんすくない · 5まい');
  await expect(dialog).toContainText('1,250 COIN');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const canvas = dialog.locator('canvas');
  const box = (await canvas.boundingBox())!;
  await page.mouse.move(box.x + 100, box.y + 100);
  await page.mouse.down();
  await page.mouse.move(box.x + 200, box.y + 200, { steps: 12 });
  await page.mouse.up();
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0); await expect(button).toBeFocused();
  await button.click(); await page.getByRole('button', { name: 'とじる' }).click();
  await expect(dialog).toHaveCount(0);
  balance = 0; await page.reload(); await button.click();
  await expect(dialog).toContainText('まだコインがないよ');
  await page.keyboard.press('Escape');
  balance = 1000000000000; await page.reload(); await button.click();
  await expect(dialog).toContainText('いちぶをみせているよ');
  expect(errors).toEqual([]);
});
