import {test,expect} from '@playwright/test';
test('family flow, remembered URLs and mobile layout',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async(value:string)=>{(window as any).copiedUrl=value;}}});});
 await page.goto('/');await page.getByLabel('銀行名',{exact:true}).fill('太郎銀行');await page.getByLabel('通貨名',{exact:true}).fill('太郎コイン');await page.getByLabel('通貨単位').fill('TARO');await page.getByRole('button',{name:'銀行を作る',exact:true}).click();
 await expect(page.getByText('銀行ができました。管理URLを保存しましょう')).toBeVisible();const bankUrl=page.url();await expect(page.getByText('他人には共有しないでください。')).toBeVisible();
 await page.getByLabel('新しいウォレットの名前').fill('太郎');await page.getByRole('button',{name:'ウォレットを作る',exact:true}).click();await expect(page.getByRole('heading',{name:'「太郎」のウォレットができました',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0);const aUrl=await page.getByLabel('秘密URL',{exact:true}).inputValue();
 await page.getByLabel('新しいウォレットの名前').fill('パパ');await page.getByRole('button',{name:'ウォレットを作る',exact:true}).click();await expect(page.getByLabel('秘密URL',{exact:true})).not.toHaveValue(aUrl);const bUrl=await page.getByLabel('秘密URL',{exact:true}).inputValue();
 await page.getByLabel('送り先').selectOption({label:'太郎'});await page.getByLabel('金額（TARO）').fill('30');await page.getByLabel('メモ',{exact:true}).fill('おふろ洗い');await page.getByRole('button',{name:'発行して送る',exact:true}).click();await expect(page.getByRole('status')).toHaveText('通貨を発行して送りました');
 await page.goto(aUrl);await expect(page.locator('.balance-card strong')).toHaveText('30 TARO');await expect(page.locator('.entry')).toContainText('おふろ洗い');await page.getByLabel('送り先').selectOption({label:'パパ'});await page.getByLabel('金額（TARO）').fill('20');await page.getByLabel('メモ',{exact:true}).fill('アイス代');await page.getByRole('button',{name:'送金する',exact:true}).click();await expect(page.locator('.balance-card strong')).toHaveText('10 TARO');await expect(page.locator('.entry').filter({hasText:'アイス代'})).toContainText('-20');
 await page.goto(bUrl);await expect(page.locator('.balance-card strong')).toHaveText('20 TARO');await expect(page.locator('.entry')).toContainText('太郎から');await page.goto('/');await expect(page.getByRole('link',{name:'太郎銀行 開く →'})).toBeVisible();await expect(page.getByRole('link',{name:'太郎 開く →'})).toBeVisible();await expect(page.getByRole('link',{name:'パパ 開く →'})).toBeVisible();await page.getByRole('link',{name:'太郎銀行 開く →'}).click();await expect(page).toHaveURL(bankUrl);
 const names=await page.locator('.wallet-name>span').allTextContents();expect(names).toEqual([...names].sort((a,b)=>a.localeCompare(b,'ja')));
 await page.locator('.wallet-row').filter({hasText:'太郎'}).getByRole('button',{name:'秘密URLをコピー',exact:true}).click();await expect(page.locator('.toast')).toHaveText('秘密URLをコピーしました');expect(await page.evaluate(()=>(window as any).copiedUrl)).toBe(aUrl);await expect(page.locator('.toast')).toHaveCount(0,{timeout:5000});
 await page.setViewportSize({width:390,height:844});await page.goto(aUrl);await expect(page.locator('.balance-card strong')).toHaveText('10 TARO');
 const bankToken=new URL(bankUrl).searchParams.get('k')!;const walletToken=new URL(aUrl).searchParams.get('k')!;const info=await (await page.request.get('/api/wallet',{headers:{Authorization:`Bearer ${walletToken}`}})).json();await page.request.post('/api/bank/issue',{headers:{Authorization:`Bearer ${bankToken}`},data:{toId:info.wallet.id,amount:5,memo:'追加',requestId:crypto.randomUUID()}});await page.getByRole('button',{name:'残高を更新',exact:true}).click();await expect(page.locator('.balance-card strong')).toHaveText('15 TARO');await expect(page.locator('.entry').filter({hasText:'追加'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('kanji switch persists across browsers, stays wallet-specific and covers wallet copy',async({page,browser})=>{
 const bank=await (await page.request.post('/api/banks',{data:{name:'ぎんこう',currencyName:'コイン',unit:'COIN'}})).json();
 const make=async(name:string)=>(await page.request.post('/api/bank/wallets',{headers:{Authorization:`Bearer ${bank.token}`},data:{name}})).json();
 const a=await make('たろう'),b=await make('パパ');
 await page.goto(`/wallet?k=${a.token}`);const toggle=page.getByRole('switch',{name:'かんじ'});await expect(toggle).toBeChecked();await toggle.click();await expect(toggle).not.toBeChecked();await expect(page.getByRole('heading',{name:'コインのきろく'})).toBeVisible();expect(await page.locator('body').innerText()).not.toMatch(/\p{Script=Han}/u);
 await page.reload();await expect(toggle).not.toBeChecked();await page.goto(`/wallet?k=${b.token}`);await expect(toggle).toBeChecked();
 const context=await browser.newContext();const other=await context.newPage();await other.goto(`http://127.0.0.1:5173/wallet?k=${a.token}`);await expect(other.getByRole('switch',{name:'かんじ'})).not.toBeChecked();await other.getByRole('button',{name:'コインをたしかめる'}).click();await expect(other.locator('.toast')).toHaveText('コインときろくをあたらしくしました');expect(await other.locator('body').innerText()).not.toMatch(/\p{Script=Han}/u);await context.close();
 await page.goto(`/bank?k=${bank.token}`);await expect(page.getByRole('switch')).toHaveCount(0);
 await page.request.post('/api/bank/issue',{headers:{Authorization:`Bearer ${bank.token}`},data:{toId:a.id,amount:30,memo:'おふろ',requestId:crypto.randomUUID()}});
 await page.goto(`/wallet?k=${a.token}`);await page.getByLabel('おくるあいて').selectOption({label:'パパ'});await page.getByLabel('コインのかず（COIN）').fill('10');await page.getByRole('button',{name:'おくる',exact:true}).click();await expect(page.locator('.toast')).toHaveText('おくりました');await expect(page.locator('.balance-card strong')).toHaveText('20 COIN');expect(await page.locator('body').innerText()).not.toMatch(/\p{Script=Han}/u);
 await toggle.click();await expect(toggle).toBeChecked();await expect(page.getByRole('heading',{name:'入出金の履歴'})).toBeVisible();
});
