import {test,expect} from '@playwright/test';
test('family flow, remembered URLs and mobile layout',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByLabel('銀行名',{exact:true}).fill('太郎銀行');await page.getByLabel('通貨名',{exact:true}).fill('太郎コイン');await page.getByLabel('通貨単位').fill('TARO');await page.getByRole('button',{name:'銀行を作る',exact:true}).click();
 await expect(page.getByText('銀行ができました。管理URLを保存しましょう')).toBeVisible();const bankUrl=page.url();await expect(page.getByText('他人には共有しないでください。')).toBeVisible();
 await page.getByLabel('新しいウォレットの名前').fill('太郎');await page.getByRole('button',{name:'ウォレットを作る',exact:true}).click();await expect(page.getByRole('heading',{name:'ウォレットができました',exact:true})).toBeVisible();const aUrl=await page.getByLabel('秘密URL',{exact:true}).inputValue();
 await page.getByLabel('新しいウォレットの名前').fill('パパ');await page.getByRole('button',{name:'ウォレットを作る',exact:true}).click();await expect(page.getByLabel('秘密URL',{exact:true})).not.toHaveValue(aUrl);const bUrl=await page.getByLabel('秘密URL',{exact:true}).inputValue();
 await page.getByLabel('送り先').selectOption({label:'太郎'});await page.getByLabel('金額（TARO）').fill('30');await page.getByLabel('メモ',{exact:true}).fill('おふろ洗い');await page.getByRole('button',{name:'発行して送る',exact:true}).click();await expect(page.getByRole('status')).toHaveText('通貨を発行して送りました。');
 await page.goto(aUrl);await expect(page.locator('.balance-card strong')).toHaveText('30 TARO');await expect(page.locator('.entry')).toContainText('おふろ洗い');await page.getByLabel('送り先').selectOption({label:'パパ'});await page.getByLabel('金額（TARO）').fill('20');await page.getByLabel('メモ',{exact:true}).fill('アイス代');await page.getByRole('button',{name:'送金する',exact:true}).click();await expect(page.locator('.balance-card strong')).toHaveText('10 TARO');await expect(page.locator('.entry').filter({hasText:'アイス代'})).toContainText('-20');
 await page.goto(bUrl);await expect(page.locator('.balance-card strong')).toHaveText('20 TARO');await expect(page.locator('.entry')).toContainText('太郎から');await page.goto('/');await expect(page.getByRole('link',{name:'太郎銀行 開く →'})).toBeVisible();await expect(page.getByRole('link',{name:'太郎 開く →'})).toBeVisible();await expect(page.getByRole('link',{name:'パパ 開く →'})).toBeVisible();await page.getByRole('link',{name:'太郎銀行 開く →'}).click();await expect(page).toHaveURL(bankUrl);
 await page.setViewportSize({width:390,height:844});await page.goto(aUrl);await expect(page.locator('.balance-card strong')).toHaveText('10 TARO');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
